language: cpp
sudo: required

before_install:
  -  APMDIR=$(pwd) && pushd .. && $APMDIR/Tools/scripts/install-travis-env.sh -y && . ~/.profile && popd

script: 
  - Tools/scripts/build_all_travis.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e5e0b55e353e53945b4b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "FjIwqZQV2FhNPWYITX5LZXTE38yYqBaQdbm3QmbEg/30wnPTm1ZOLIU7o/aSvX615ImR8kHoryvFPDQDWc6wWfqTEs3Ytq2kIvcIJS2Y5l/0PFfpWJoH5gRd6hDThnoi+1oVMLvj1+bhn4yFlCCQ2vT/jxoGfiQqqgvHtv4fLzI="
  matrix:
    - TRAVIS_BUILD_TARGET="px4-v2"
    - TRAVIS_BUILD_TARGET="sitl linux navio raspilot minlure"

addons:
  coverity_scan:
    project:
      name: "diydrones/ardupilot"
      description: "Build submitted via Travis CI"
    notification_email: andrew-scan@tridgell.net
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
